import os, sys, subprocess

quad = subprocess.Popen(['python', 'quad.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
quad1 = subprocess.Popen(['python', 'quad.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
quad2 = subprocess.Popen(['python', 'quad.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
quad3 = subprocess.Popen(['python', 'quad.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
quad4 = subprocess.Popen(['python', 'quad.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
bird = subprocess.Popen(['python', 'bird.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
bird1 = subprocess.Popen(['python', 'bird.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
bird2 = subprocess.Popen(['python', 'bird.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
bird3 = subprocess.Popen(['python', 'bird.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
bird4 = subprocess.Popen(['python', 'bird.py'], shell=True, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
quad.communicate()
quad1.communicate()
quad2.communicate()
quad3.communicate()
quad4.communicate()
bird.communicate()
bird1.communicate()
bird2.communicate()
bird3.communicate()
bird4.communicate()
